Traceback (most recent call last):
  File "/home/gen_sim/gensim/sim_runner.py", line 189, in simulate_task
    total_reward = self.run_one_episode(dataset, expert, env, task, episode, seed)
  File "/home/gen_sim/gensim/sim_runner.py", line 143, in run_one_episode
    act = expert.act(obs, info)
  File "/home/gen_sim/cliport/tasks/task.py", line 119, in act
    if self.is_match(pose, targs[j], symmetry):
IndexError: list index out of range
